// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7YZbQHVRzfAu-TgZFAeV-Ji5OBNj-L5I',
    appId: '1:579972436408:web:44d60f167ccc176cb33f4d',
    messagingSenderId: '579972436408',
    projectId: 'pocketnotesapp',
    authDomain: 'pocketnotesapp.firebaseapp.com',
    storageBucket: 'pocketnotesapp.appspot.com',
    measurementId: 'G-1KXZLXBV2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx0S5X-UDJ_Yn3mAXLMrYtmpC8LcQbBaI',
    appId: '1:579972436408:android:b5390a3f7c9b0526b33f4d',
    messagingSenderId: '579972436408',
    projectId: 'pocketnotesapp',
    storageBucket: 'pocketnotesapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1e59Y-GviUm6Zp0eQklRRPfSGlxw34Ps',
    appId: '1:579972436408:ios:f82c15d27ab66e20b33f4d',
    messagingSenderId: '579972436408',
    projectId: 'pocketnotesapp',
    storageBucket: 'pocketnotesapp.appspot.com',
    iosClientId: '579972436408-bq3j1g1hpk1q63j07glqeduvojbsthmc.apps.googleusercontent.com',
    iosBundleId: 'com.PocketNotes.pocketnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1e59Y-GviUm6Zp0eQklRRPfSGlxw34Ps',
    appId: '1:579972436408:ios:f82c15d27ab66e20b33f4d',
    messagingSenderId: '579972436408',
    projectId: 'pocketnotesapp',
    storageBucket: 'pocketnotesapp.appspot.com',
    iosClientId: '579972436408-bq3j1g1hpk1q63j07glqeduvojbsthmc.apps.googleusercontent.com',
    iosBundleId: 'com.PocketNotes.pocketnotes',
  );
}
